### ISSUE TITLE
Task "Add RabbitMQ repository" fails with "apt.cache.FetchFailedException" error

### ISSUE THREAD

**Issue by ThomasVille** [Stouts/Stouts.rabbitmq#9]
Hi,

On Ubuntu 18.04, when running the role `Stouts.rabbitmq`, the task `Add RabbitMQ repository` fails with the following output:
```
    dev-image: TASK [include_role : Stouts.rabbitmq] ******************************************
    dev-image: 
    dev-image: TASK [Stouts.rabbitmq : Add RabbitMQ key] **************************************
    dev-image: changed: [dev-image]
    dev-image: 
    dev-image: TASK [Stouts.rabbitmq : Add RabbitMQ repository] *******************************
    dev-image: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'http://www.rabbitmq.com/debian testing Release' does not have a Release file.
    dev-image: fatal: [dev-image]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1612460983.32-163575430444603/AnsiballZ_apt_repository.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1612460983.32-163575430444603/AnsiballZ_apt_repository.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1612460983.32-163575430444603/AnsiballZ_apt_repository.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_apt_repository_payload_J1E2W8/__main__.py\", line 550, in <module>\n  File \"/tmp/ansible_apt_repository_payload_J1E2W8/__main__.py\", line 542, in main\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 586, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'http://www.rabbitmq.com/debian testing Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

When checking the page [Installing on Debian and Ubuntu](https://www.rabbitmq.com/install-debian.html) of the documentation of RabbitMQ, I can't find any mention of http://www.rabbitmq.com/debian and the 2 recommended ways to install RabbitMQ are either using BinTray or PackageCloud.

So I believe the URL of the repository is now out of date.
